Migration.Toolkit.Common/Helpers/DeferrableItemEnumerableWrapper.cs
Migration.Toolkit.Common/Helpers/EnumerableHelper.cs
Migration.Toolkit.Common/Helpers/SimpleAligner.cs
Migration.Toolkit.Core/Contexts/PrimaryKeyMappingContext.cs
Migration.Toolkit.Core/Handlers/MigratePageTypesCommandHandler.cs
Migration.Toolkit.Core/Helpers/EntityPrinter.cs
Migration.Toolkit.Core/LogExtensions.cs

#37 correct migration of Page types with inheritance

---

Migration.Toolkit.CLI/ConfigurationValidator.cs
Migration.Toolkit.CLI/ConsoleHelper.cs
Migration.Toolkit.CLI/Program.cs
Migration.Toolkit.Common/EntityConfiguration.cs
Migration.Toolkit.Common/Extensions.cs
Migration.Toolkit.Common/ToolkitConfiguration.cs
Migration.Toolkit.Core/Handlers/MigratePageTypesCommandHandler.cs
Migration.Toolkit.Core/Helpers/Printer.cs
Migration.Toolkit.Core/LogExtensions.cs
Migration.Toolkit.Core/MigrationProtocol/HandbookReference.cs

Which issue does this fix? Fixes #40

40 configuration parameters validation create meaningful errors warnings for invalid configuration

---

Migration.Toolkit.CLI/MIGRATION_PROTOCOL_REFERENCE.md
Migration.Toolkit.CLI/README.md
Migration.Toolkit.KXP.Extensions/README.MD
README.md

Documentation update after the most recent attachment migration improvements, including the handler for legacy attachment URLs. Also includes some general improvements and changes.
The documentation should be consistent with the migration toolkit after [Issue 52](https://github.com/Kentico/xperience-migration-toolkit/issues/52) and [Issue 54](https://github.com/Kentico/xperience-migration-toolkit/issues/54) are implemented.

Davidb doc update after attachment conversion

---

Migration.Toolkit.Core/Extensions.cs
Migration.Toolkit.Core/Handlers/MigratePagesCommandHandler.cs
Migration.Toolkit.Core/Mappers/CmsClassMapper.cs
Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs
Migration.Toolkit.KX13/Auxiliary/Kx13FieldDataType.cs
Migration.Toolkit.KXP.Api/Auxiliary/FormComponents.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj

Which issue does this fix? Fixes #54

#54 migration of form definition & value conversions

---

Migration.Toolkit.Core/Abstractions/ModelMappingResult.cs
Migration.Toolkit.Core/DependencyInjectionExtensions.cs
Migration.Toolkit.Core/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core/Helpers/Printer.cs
Migration.Toolkit.Core/Mappers/CountryInfoMapper.cs
Migration.Toolkit.Core/Mappers/StateInfoMapper.cs
Migration.Toolkit.Core/Services/CountryMigrator.cs
Migration.Toolkit.Core/Services/PrimaryKeyLocatorService.cs
Migration.Toolkit.TestConsole/Program.cs

Which issue does this fix? Fixes #52

#52 Country & State migration

---

Migration.Toolkit.CLI/Program.cs
Migration.Toolkit.Common/SemanticVersion.cs
Migration.Toolkit.Core/Abstractions/CommandResult.cs
Migration.Toolkit.Core/Behaviors/CommandConstraintBehavior.cs
Migration.Toolkit.Core/Commands.cs
Migration.Toolkit.Core/DependencyInjectionExtensions.cs
Migration.Toolkit.Core/Handlers/MigrateDataProtectionCommandHandler.cs
Migration.Toolkit.Core/Handlers/MigratePagesCommandHandler.cs
Migration.Toolkit.Core/Mappers/CmsClassMapper.cs
Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs
Migration.Toolkit.Core/MigrationProtocol/HandbookReferences.cs
Migration.Toolkit.KXP.Api/KxpSiteFacade.cs

Which issue does this fix? Fixes #56

#56 command constraint check

---

Migration.Toolkit.Core/Handlers/MigratePagesCommandHandler.cs
Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs

Which issue does this fix? Fixes #67

#67 respecting node order from source kx instance

---

Migration.Toolkit.Core/Mappers/CmsClassMapper.cs

Which issue does this fix? Fixes #69

#69 class mapper too strict on ClassResourceId migration

---

Migration.Toolkit.Core/Behaviors/RequestHandlingBehavior.cs
Migration.Toolkit.Core/Handlers/MigratePagesCommandHandler.cs
Migration.Toolkit.Core/LogExtensions.cs

Which issue does this fix? Fixes #72

#72 wrong assertion fix - node has always doc in culture

---

Migration.Toolkit.Core/Handlers/MigratePageTypesCommandHandler.cs
Migration.Toolkit.Core/Handlers/MigratePagesCommandHandler.cs
Migration.Toolkit.Core/Mappers/CmsClassMapper.cs
Migration.Toolkit.Core/Services/PrimaryKeyLocatorService.cs

Which issue does this fix? Fixes #76

#76 instance of page doesn't have class active for site

---

Migration.Toolkit.Core/Handlers/MigrateAttachmentsCommandHandler.cs
Migration.Toolkit.Core/Mappers/CmsClassMapper.cs
Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs
Migration.Toolkit.Core/Services/AttachmentMigrator.cs
Migration.Toolkit.Core/Services/CmsClass/FormFieldMappingModel.cs
Migration.Toolkit.KXP.Extensions/LegacyAttachmentHandler.cs

Which issue does this fix? Fixes #81 #80

#81 #80 legacy attachment handler optimization + ff mapping bugfix

---

Migration.Toolkit.CLI/README.md
README.md

Which issue does this fix? Documentation #79

#79 formfield formcomponent formcontrol update for xbk v2220

---

.editorconfig
Migration.Toolkit.Core/Handlers/MigratePagesCommandHandler.cs
Migration.Toolkit.Core/Helpers/Printer.cs
Migration.Toolkit.Core/MigrationProtocol/HandbookReferences.cs

Which issue does this fix? Fixes #85

#85 logging improvements

---

Migration.Toolkit.CLI/ConfigurationValidator.cs
Migration.Toolkit.CLI/Program.cs
Migration.Toolkit.CLI/appsettings.json
Migration.Toolkit.Common/ConfigurationNames.cs
Migration.Toolkit.Common/Extensions.cs
Migration.Toolkit.Common/Migration.Toolkit.Common.csproj
Migration.Toolkit.Common/OptInFeatures.cs
Migration.Toolkit.Common/Resources.Designer.cs
Migration.Toolkit.Common/Resources.resx
Migration.Toolkit.Common/ToolkitConfiguration.cs
Migration.Toolkit.Core/Handlers/MigrateMediaLibrariesCommandHandler.cs
Migration.Toolkit.Core/Services/BulkCopy/BulkDataCopyService.cs
Migration.Toolkit.Core/Services/CoupledDataService.cs
Migration.Toolkit.KX13/DependencyInjectionExtensions.cs
Migration.Toolkit.KXP/DependencyInjectionExtensions.cs
Migration.Toolkit.TestConsole/Program.cs

Which issue does this fix? Fixes #86

#86 configuration naming optimization

---

Migration.Toolkit.CLI/README.md

Which issue does this fix? Fixes #96 ; #86

#96 docs changes related to #86

---

Migration.Toolkit.Core/Mappers/CmsClassMapper.cs
Migration.Toolkit.Core/Services/CmsClass/FormFieldMappingModel.cs

Which issue does this fix? Fixes #98

#98 field with no control set SHALL NOT be visible

---

Migration.Toolkit.CLI/Program.cs
Migration.Toolkit.Core/Mappers/MediaFileInfoMapper.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Tests/autorun/.gitignore
Tests/autorun/i-kxo-empty.ps1
Tests/autorun/run-test.ps1

Which issue does this fix? Fixes #101 #106

101 migratemedialibrary xbk api cmsmedialibrarymedialibraryinfo requires ihttpcontextaccessor

---

Migration.Toolkit.CLI/Program.cs
Migration.Toolkit.Core/Mappers/MediaFileInfoMapper.cs
Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Tests/autorun/.gitignore
Tests/autorun/i-kxo-empty.ps1
Tests/autorun/run-test.ps1

Which issue does this fix? Fixes #107

107 changes related to content hub

---

Migration.Toolkit.Core/Behaviors/CommandConstraintBehavior.cs

Which issue does this fix? Fixes #87

#87 sql database collation constraint

---

Migration.Toolkit.Core/Handlers/MigrateUsersCommandHandler.cs
Migration.Toolkit.Core/Mappers/UserRoleInfoMapper.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Tests/autorun/run-test.ps1

Which issue does this fix? Fixes #112

#112 upgrade to XbK Api 23.0.0

---

Migration.Toolkit.Core/Handlers/MigrateUsersCommandHandler.cs
Migration.Toolkit.KXP.Api/Enums/UserPrivilegeLevelEnum.cs

Which issue does this fix? Fixes #114

#114 UserPrivilegeLevel filter

---

Migration.Toolkit.Core/Behaviors/CommandConstraintBehavior.cs
Migration.Toolkit.Core/Behaviors/XbKApiContextBehavior.cs
Migration.Toolkit.Core/Contexts/PrimaryKeyMappingContext.cs
Migration.Toolkit.Core/DependencyInjectionExtensions.cs
Migration.Toolkit.Core/Handlers/MigrateCustomModulesCommandHandler.cs
Migration.Toolkit.Core/Handlers/MigrateUsersCommandHandler.cs
Migration.Toolkit.Core/Helpers/Printer.cs
Migration.Toolkit.Core/Mappers/RoleInfoMapper.cs
Migration.Toolkit.Core/MigrationProtocol/HandbookReferences.cs
Migration.Toolkit.Core/Services/PrimaryKeyLocatorService.cs
Migration.Toolkit.KX13/KX13ContextCustomizations.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Migration.Toolkit.sln.DotSettings.user
global.json

Which issue does this fix? Fixes #112

#112 user role & role migration

---

Migration.Toolkit.Core/Services/CmsClass/FormDefinitionPatcher.cs

Which issue does this fix? Fixes #118

#118 module class form definition migration fix

---

Migration.Toolkit.CLI/README.md
README.md

Motivation
Documentation for roles migration support.
Issues:
#119

112 documentation roles support

---

Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs

Which issue does this fix? Fixes #126

#126 document PublishedTo was set to DateTime.MinValue DB incorrectly

---

Migration.Toolkit.CLI/ConfigurationValidator.cs
Migration.Toolkit.Common/ConfigurationNames.cs
Migration.Toolkit.Common/Helpers/MediaHelper.cs
Migration.Toolkit.Common/OptInFeatures.cs
Migration.Toolkit.Common/ToolkitConfiguration.cs
Migration.Toolkit.Core/DependencyInjectionExtensions.cs
Migration.Toolkit.Core/Mappers/AlternativeFormMapper.cs
Migration.Toolkit.Core/Mappers/CmsClassMapper.cs
Migration.Toolkit.Core/Mappers/PageTemplateConfigurationMapper.cs
Migration.Toolkit.Core/Mappers/TreeNodeMapper.cs
Migration.Toolkit.Core/Services/AttachmentMigrator.cs
Migration.Toolkit.Core/Services/CmsClass/ClassService.cs
Migration.Toolkit.Core/Services/CmsClass/FormDefinitionPatcher.cs
Migration.Toolkit.Core/Services/CmsClass/FormFieldMappingModel.cs
Migration.Toolkit.Core/Services/FieldMigrationService.cs
Migration.Toolkit.KXP.Api/KxpMediaFileFacade.cs
Migration.Toolkit.Tests/MediaHelperTest.cs
Migration.Toolkit.Tests/Migration.Toolkit.Tests.csproj
Migration.Toolkit.Tests/Usings.cs
Migration.Toolkit.sln

Which issue does this fix? Fixes #125

#125 customization of field migrations

---

Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Migration.Toolkit.KXP/Context/KxpContext.cs
Migration.Toolkit.KXP/Models/CmsContentRelationship.cs
Migration.Toolkit.KXP/Models/CmsContentRelationshipItem.cs
Migration.Toolkit.KXP/Models/CmsFormFeaturedField.cs

Which issue does this fix? Fixes #134

#134 XbK nuget upgrade 21.1.0 & EF classes refresh

---

Migration.Toolkit.CLI/README.md
README.md

Documentation media text fields

---

KVA/Migration.Toolkit.Source/Migration.Toolkit.Source.csproj
Migration.Toolkit.CLI/Program.cs
Migration.Toolkit.CLI/appsettings.json
Migration.Toolkit.Common/ConfigurationNames.cs
Migration.Toolkit.Common/Helpers/TreePathConvertor.cs
Migration.Toolkit.Common/Migration.Toolkit.Common.csproj
Migration.Toolkit.Core.KX13/Migration.Toolkit.Core.KX13.csproj
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj

upgrade of Xperience by Kentico API to recent version v29.0.2.
upgrade of Xperience by Kentico Universal migration toolkit to recent version v1.0.4

MT-1 upgrade to v29.0.2 and UMT upgrade to v1.0.4

---

KVA/Migration.Toolkit.Source/Migration.Toolkit.Source.csproj
Migration.Toolkit.CLI/appsettings.json
Migration.Toolkit.Common/Migration.Toolkit.Common.csproj
Migration.Toolkit.Core.K11/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core.K11/Handlers/MigrateSettingKeysCommandHandler.cs
Migration.Toolkit.Core.KX12/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core.KX12/Handlers/MigrateSettingKeysCommandHandler.cs
Migration.Toolkit.Core.KX13/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core.KX13/Handlers/MigrateSettingKeysCommandHandler.cs
Migration.Toolkit.Core.KX13/Migration.Toolkit.Core.KX13.csproj
Migration.Toolkit.Core.KX13/Services/PrimaryKeyLocatorService.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Migration.Toolkit.KXP/Context/KxpContext.cs
Migration.Toolkit.KXP/Models/CmsContentFolder.cs
Migration.Toolkit.KXP/Models/CmsContentItem.cs
Migration.Toolkit.KXP/Models/CmsContentItemLanguageMetadatum.cs
Migration.Toolkit.KXP/Models/CmsContentItemTag.cs
Migration.Toolkit.KXP/Models/CmsResource.cs
Migration.Toolkit.KXP/Models/CmsScheduledTask.cs
Migration.Toolkit.KXP/Models/CmsUser.cs

upgrade of XbyK API v29.1.0 and UMT v1.0.5.

Upgrade of UMT v1.0.5 and XbyK API v29.1.0

---

KVA/Migration.Toolkit.Source/Mappers/MemberInfoMapper.cs
KVA/Migration.Toolkit.Source/Migration.Toolkit.Source.csproj
Migration.Toolkit.CLI/appsettings.json
Migration.Toolkit.Common/Enumerations/Kx13SystemClasses.cs
Migration.Toolkit.Common/Migration.Toolkit.Common.csproj
Migration.Toolkit.Core.K11/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core.K11/Handlers/MigrateMembersCommandHandler.cs
Migration.Toolkit.Core.K11/Handlers/MigrateSettingKeysCommandHandler.cs
Migration.Toolkit.Core.K11/Mappers/MemberInfoMapper.cs
Migration.Toolkit.Core.KX12/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core.KX12/Handlers/MigrateMembersCommandHandler.cs
Migration.Toolkit.Core.KX12/Handlers/MigrateSettingKeysCommandHandler.cs
Migration.Toolkit.Core.KX12/Mappers/MemberInfoMapper.cs
Migration.Toolkit.Core.KX13/Handlers/MigrateContactManagementCommandHandler.cs
Migration.Toolkit.Core.KX13/Handlers/MigrateMembersCommandHandler.cs
Migration.Toolkit.Core.KX13/Handlers/MigrateSettingKeysCommandHandler.cs
Migration.Toolkit.Core.KX13/Mappers/MemberInfoMapper.cs
Migration.Toolkit.Core.KX13/Migration.Toolkit.Core.KX13.csproj
Migration.Toolkit.Core.KX13/Services/PrimaryKeyLocatorService.cs
Migration.Toolkit.KXP.Api/KxpClassFacade.cs
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Migration.Toolkit.KXP/Context/KxpContext.cs
Migration.Toolkit.KXP/Models/CmsContentFolder.cs
Migration.Toolkit.KXP/Models/CmsContentItem.cs
Migration.Toolkit.KXP/Models/CmsContentItemLanguageMetadatum.cs
Migration.Toolkit.KXP/Models/CmsContentItemTag.cs
Migration.Toolkit.KXP/Models/CmsResource.cs
Migration.Toolkit.KXP/Models/CmsScheduledTask.cs
Migration.Toolkit.KXP/Models/CmsUser.cs

Which issue does this fix? Fixes #179
please pull after PR #180

Member custom field data synchronization fix

---

README.md

XbyK supported version update v29.1.0

Update README.md - supported version

---

KVA/Migration.Toolkit.Source/Extensions.cs
KVA/Migration.Toolkit.Source/Handlers/MigrateCategoriesCommandHandler.cs
KVA/Migration.Toolkit.Source/KsCoreDiExtensions.cs
KVA/Migration.Toolkit.Source/Mappers/TagMapper.cs
KVA/Migration.Toolkit.Source/Model/CmsCategory.cs
KVA/Migration.Toolkit.Source/Model/CmsDocumentCategory.cs
KVA/Migration.Toolkit.Source/Model/OmActivity.cs
KVA/Migration.Toolkit.Source/ModelFacade.cs
KVA/Migration.Toolkit.Source/Services/ReusableSchemaService.cs
Migration.Toolkit.Common/Commands.cs
Migration.Toolkit.Common/Helpers/GuidHelper.cs
Migration.Toolkit.Common/Migration.Toolkit.Common.csproj
Migration.Toolkit.Common/Services/CommandParser.cs

this PR implement variant of category migration from source instance for all source instance types

MT-2 taxonomy migration

---

KVA/Migration.Toolkit.Source/Mappers/CmsClassMapper.cs
KVA/Migration.Toolkit.Source/Mappers/ContentItemMapper.cs
Migration.Toolkit.Common/Helpers/GuidHelper.cs

Which issue does this fix? Fixes #185, it may fix #186. This PR updates behaviour of DocumentName field GUID generation to avoid conflicts in CI.

Document name field guid generation update

---

Migration.Toolkit.KXP/Context/KxpContext.cs

Which issue does this fix? Fixes #196

#196 removal of hardcoded connection string

---

.github/workflows/build.yml
Migration.Toolkit.Tests/MediaHelperTest.cs
global.json

Setup correct dotnet version in order to fix CI pipeline. 
- Disabling failing test cases - We do not support custom media file URLs.
If manual testing is required, what are the steps?

Setup correct dotnet version

---

docs/Usage-Guide.md

- More details around migration path options to help orient developers
n/a

Feature: add migration paths tables

---

KVA/Migration.Toolkit.Source/Mappers/MediaLibraryInfoMapper.cs

Which issue does this fix? Fixes #230

safer target library name fallback

---

KVA/Migration.Toolkit.Source/Handlers/MigratePagesCommandHandler.cs

K12/K11 fix
Which issue does this fix? Fixes #215

linked documents no longer generate same urls as original documents

---

KVA/Migration.Toolkit.Source/Migration.Toolkit.Source.csproj
Migration.Toolkit.Common/Migration.Toolkit.Common.csproj
Migration.Toolkit.Core.KX13/Migration.Toolkit.Core.KX13.csproj
Migration.Toolkit.KXP.Api/Migration.Toolkit.KXP.Api.csproj
Migration.Toolkit.KXP.Extensions/Migration.Toolkit.KXP.Extensions.csproj
Migration.Toolkit.Tests/Migration.Toolkit.Tests.csproj

upgrade to UMT 1.7.0

---

README.md

version matrix update for version 1.3.0

version matrix update for version 1.3.0

---

Migration.Toolkit.CLI/README.md
Migration.Toolkit.KXP.Extensions/README.MD

Review for changes in #255 and related to #244

Asset migration review

---

KVA/Migration.Tool.Source/Migration.Tool.Source.csproj
Migration.Tool.Common/Migration.Tool.Common.csproj
Migration.Tool.Core.KX13/Migration.Tool.Core.KX13.csproj
Migration.Tool.KXP.Api/Migration.Tool.KXP.Api.csproj
Migration.Tool.KXP.Extensions/Migration.Tool.KXP.Extensions.csproj
Migration.Tool.Tests/Migration.Tool.Tests.csproj

requested upgrade to XbyK 29.7.0 and UMT 1.10.1

upgrade of deps XbyK 29.7.0 and UMT 1.10.1

---

.github/CODEOWNERS

Which issue does this fix? 
Updating codeowners file

Update and rename .CODEOWNERS to CODEOWNERS

---

KVA/Migration.Tool.Source/Handlers/MigrateCategoriesCommandHandler.cs
Migration.Tool.Common/Builders/ClassMapper.cs
Migration.Tool.Extensions/ClassMappings/ClassMappingSample.cs
Migration.Tool.Extensions/README.md

Add: Support category migration for mapped classes
Fixes issue https://github.com/orgs/Kentico/projects/15/views/1?pane=issue&itemId=88274814&issue=Kentico%7Cxperience-by-kentico-kentico-migration-tool%7C300 
Map a class that has docs which have some categories using class mapping. You can use AddControlledCategoryMigrationSample on official Kentico 11 eshop demo.

Support category migration for mapped classes
